// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_A_CFG_CALIBRATE_MODE

namespace BulkMaterialsForm.DH;

public enum EM_A_CFG_CALIBRATE_MODE
{
	CFG_CALIBRATE_MODE_UNKOWN,
	CFG_CALIBRATE_MODE_ORIGIAL,
	CFG_CALIBRATE_MODE_CONFIG,
	CFG_CALIBRATE_MODE_PANORAMA,
	CFG_CALIBRATE_MODE_DOUBLEPANORAMA,
	CFG_CALIBRATE_MODE_ORIGIALPLUSTHREEEPTZREGION,
	CFG_CALIBRATE_MODE_SINGLE,
	CFG_CALIBRATE_MODE_FOUREPTZREGION,
	CFG_CALIBRATE_MODE_NORMAL
}
