// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_A_NET_ENUM_USER_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_A_NET_ENUM_USER_TYPE
{
	NET_ENUM_USER_TYPE_UNKNOWN = -1,
	NET_ENUM_USER_TYPE_NORMAL,
	NET_ENUM_USER_TYPE_BLACKLIST,
	NET_ENUM_USER_TYPE_GUEST,
	NET_ENUM_USER_TYPE_PATROL,
	NET_ENUM_USER_TYPE_VIP,
	NET_ENUM_USER_TYPE_HANDICAP,
	NET_ENUM_USER_TYPE_CUSTOM1,
	NET_ENUM_USER_TYPE_CUSTOM2
}
