// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_A_NET_ACCESSCTLCARD_STATE

namespace BulkMaterialsForm.DH;

public enum EM_A_NET_ACCESSCTLCARD_STATE
{
	NET_ACCESSCTLCARD_STATE_UNKNOWN = -1,
	NET_ACCESSCTLCARD_STATE_NORMAL = 0,
	NET_ACCESSCTLCARD_STATE_LOSE = 1,
	NET_ACCESSCTLCARD_STATE_LOGOFF = 2,
	NET_ACCESSCTLCARD_STATE_FREEZE = 4,
	NET_ACCESSCTLCARD_STATE_ARREARAGE = 8,
	NET_ACCESSCTLCARD_STATE_OVERDUE = 16,
	NET_ACCESSCTLCARD_STATE_PREARREARAGE = 32
}
