// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_A_ENUM_RECORDBACKUP_FILE_PROGRESS_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_A_ENUM_RECORDBACKUP_FILE_PROGRESS_TYPE
{
	ENUM_RECORDBACKUP_FILE_PROGRESS_UNKNOWN,
	ENUM_RECORDBACKUP_FILE_PROGRESS_HEADER_PACKAGE,
	ENUM_RECORDBACKUP_FILE_PROGRESS_INDEX_PACKAGE,
	ENUM_RECORDBACKUP_FILE_PROGRESS_STREAM_PACKET,
	ENUM_RECORDBACKUP_FILE_PROGRESS_EMPTY_PACKET
}
