// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_A_NET_WIRELESSDEV_LOWPOWER_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_A_NET_WIRELESSDEV_LOWPOWER_TYPE
{
	NET_WIRELESSDEV_UNKNOWN,
	NET_WIRELESSDEV_CONTROL,
	NET_WIRELESSDEV_DEFENCE,
	NET_WIRELESSDEV_KEYBOARD,
	NET_WIRELESSDEV_MAGNETOMER,
	NET_WIRELESSDEV_ALARMBELL,
	NET_WIRELESSDEV_SMARTLOCK
}
