// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_ANINAL_CATEGORY

namespace BulkMaterialsForm.DH;

public enum EM_ANINAL_CATEGORY
{
	EM_ANINAL_CATEGORY_UNKNOWN,
	EM_ANINAL_CATEGORY_PIG,
	EM_ANINAL_CATEGORY_CAT,
	EM_ANINAL_CATEGORY_DOG,
	EM_ANINAL_CATEGORY_BIRD,
	EM_ANINAL_CATEGORY_GOLDEN_MONKEY,
	EM_ANINAL_CATEGORY_BLACK_BECKED_CRANE
}
