// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_ANALYSE_HUMANFACE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_ANALYSE_HUMANFACE_TYPE
{
	EM_ANALYSE_HUMANFACE_TYPE_UNKNOWN,
	EM_ANALYSE_HUMANFACE_TYPE_NORMAL,
	EM_ANALYSE_HUMANFACE_TYPE_HIDEEYE,
	EM_ANALYSE_HUMANFACE_TYPE_HIDENOSE,
	EM_ANALYSE_HUMANFACE_TYPE_HIDEMOUTH,
	EM_ANALYSE_HUMANFACE_TYPE_ADJACENTFACE,
	EM_ANALYSE_HUMANFACE_TYPE_ABNORMALFACE,
	EM_ANALYSE_HUMANFACE_TYPE_HELMETFACE
}
