// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_AUDIO_MUTATION_ALARM_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_AUDIO_MUTATION_ALARM_TYPE
{
	AUDIO_MUTATION_UNKNOW,
	AUDIO_MUTATION_CRY,
	AUDIO_MUTATION_ALARM,
	AUDIO_MUTATION_GUNSHOT,
	AUDIO_MUTATION_EXPLOSION,
	AUDIO_MUTATION_SCREAM,
	AUDIO_MUTATION_CRASHINGGLASS
}
