// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_ANALYSE_TASK_ERROR

namespace BulkMaterialsForm.DH;

public enum EM_ANALYSE_TASK_ERROR
{
	EM_ANALYSE_TASK_ERROR_UNKNOWN = 1,
	EM_ANALYSE_TASK_ERROR_INSUFFICIENT_DECODING_CAPABILITY,
	EM_ANALYSE_TASK_ERROR_INSUFFICIENT_INTELLIGENCE_CAPABILITY,
	EM_ANALYSE_TASK_ERROR_BITSTREAM_FORMAT_NOT_SUPPORTED,
	EM_ANALYSE_TASK_ERROR_ANALYZER_OFF_LINE,
	EM_ANALYSE_TASK_ERROR_ANALYZER_ON_LINE
}
