// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_AREAARM_TRIGGERMODE

namespace BulkMaterialsForm.DH;

public enum EM_AREAARM_TRIGGERMODE
{
	EM_AREAARM_TRIGGERMODE_UNKNOWN,
	EM_AREAARM_TRIGGERMODE_KEYPAD,
	EM_AREAARM_TRIGGERMODE_REMOTECONTROL,
	EM_AREAARM_TRIGGERMODE_USER,
	EM_AREAARM_TRIGGERMODE_LOCAL,
	EM_AREAARM_TRIGGERMODE_TIMER,
	EM_AREAARM_TRIGGERMODE_KEY,
	EM_AREAARM_TRIGGERMODE_REMOTE,
	EM_AREAARM_TRIGGERMODE_DSS,
	EM_AREAARM_TRIGGERMODE_DSSPRO,
	EM_AREAARM_TRIGGERMODE_DMSS
}
