// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_AREAALARM_TRIGGER_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_AREAALARM_TRIGGER_TYPE
{
	EM_AREAALARM_TRIGGER_TYPE_UNKNOWN,
	EM_AREAALARM_TRIGGER_TYPE_ALARM,
	EM_AREAALARM_TRIGGER_TYPE_TAMPER,
	EM_AREAALARM_TRIGGER_TYPE_MASK,
	EM_AREAALARM_TRIGGER_TYPE_SHORT
}
