// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_ACCESSORY_ALARM_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_ACCESSORY_ALARM_TYPE
{
	EM_ACCESSORY_ALARM_UNKNOWN = -1,
	EM_ACCESSORY_ALARM_INTRUSION,
	EM_ACCESSORY_ALARM_FIRE,
	EM_ACCESSORY_ALARM_MEDICAL,
	EM_ACCESSORY_ALARM_PANIC,
	EM_ACCESSORY_ALARM_GAS,
	EM_ACCESSORY_ALARM_HOLDUP
}
