// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_ASSOCIATED_RECORD_SOURCE

namespace BulkMaterialsForm.DH;

public enum EM_ASSOCIATED_RECORD_SOURCE
{
	EM_ASSOCIATED_RECORD_SOURCE_UNKNOWN = -1,
	EM_ASSOCIATED_RECORD_SOURCE_NONE,
	EM_ASSOCIATED_RECORD_SOURCE_HUMAN,
	EM_ASSOCIATED_RECORD_SOURCE_MOTOR_VEHICLE_PASSING,
	EM_ASSOCIATED_RECORD_SOURCE_MOTOR_VEHICLE_VIOLATION,
	EM_ASSOCIATED_RECORD_SOURCE_STRUCTURED_MOTOR_VEHICLE,
	EM_ASSOCIATED_RECORD_SOURCE_FACE,
	EM_ASSOCIATED_RECORD_SOURCE_NON_MOTOR_VEHICLE
}
