// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_A_NET_ACCESS_CTL_STATUS_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_A_NET_ACCESS_CTL_STATUS_TYPE
{
	NET_ACCESS_CTL_STATUS_TYPE_UNKNOWN,
	NET_ACCESS_CTL_STATUS_TYPE_OPEN,
	NET_ACCESS_CTL_STATUS_TYPE_CLOSE,
	NET_ACCESS_CTL_STATUS_TYPE_ABNORMAL,
	NET_ACCESS_CTL_STATUS_TYPE_FAKELOCKED,
	NET_ACCESS_CTL_STATUS_TYPE_CLOSEALWAYS,
	NET_ACCESS_CTL_STATUS_TYPE_OPENALWAYS,
	NET_ACCESS_CTL_STATUS_TYPE_NORMAL
}
