// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_A_CFG_ENUM_NET_BOND_MODE

namespace BulkMaterialsForm.DH;

public enum EM_A_CFG_ENUM_NET_BOND_MODE
{
	CFG_ENUM_NET_BOND_MODE_UNKNOWN,
	CFG_ENUM_NET_BOND_MODE_BALANCERR,
	CFG_ENUM_NET_BOND_MODE_BALANCEXOR,
	CFG_ENUM_NET_BOND_MODE_BALANCETLB,
	CFG_ENUM_NET_BOND_MODE_BALANCEALB,
	CFG_ENUM_NET_BOND_MODE_ACTIVEBACKUP,
	CFG_ENUM_NET_BOND_MODE_BROADCAST,
	CFG_ENUM_NET_BOND_MODE_802_3AD,
	CFG_ENUM_NET_BOND_MODE_BRIDGE
}
