// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_A_ENUM_VAGEOBJECT_ACTION

namespace BulkMaterialsForm.DH;

public enum EM_A_ENUM_VAGEOBJECT_ACTION
{
	ENUM_VAGEOBJECT_ACTION_UNKNOWN,
	ENUM_VAGEOBJECT_ACTION_APPEAR,
	ENUM_VAGEOBJECT_ACTION_MOVE,
	ENUM_VAGEOBJECT_ACTION_STAY,
	ENUM_VAGEOBJECT_ACTION_REMOVE,
	ENUM_VAGEOBJECT_ACTION_DISAPPEAR,
	ENUM_VAGEOBJECT_ACTION_SPLIT,
	ENUM_VAGEOBJECT_ACTION_MERGE,
	ENUM_VAGEOBJECT_ACTION_RENAME
}
