// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_A_NET_ACCESSCTLCARD_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_A_NET_ACCESSCTLCARD_TYPE
{
	NET_ACCESSCTLCARD_TYPE_UNKNOWN = -1,
	NET_ACCESSCTLCARD_TYPE_GENERAL = 0,
	NET_ACCESSCTLCARD_TYPE_VIP = 1,
	NET_ACCESSCTLCARD_TYPE_GUEST = 2,
	NET_ACCESSCTLCARD_TYPE_PATROL = 3,
	NET_ACCESSCTLCARD_TYPE_BLACKLIST = 4,
	NET_ACCESSCTLCARD_TYPE_CORCE = 5,
	NET_ACCESSCTLCARD_TYPE_POLLING = 6,
	NET_ACCESSCTLCARD_TYPE_GB_CUSTOM1 = 7,
	NET_ACCESSCTLCARD_TYPE_GB_CUSTOM2 = 8,
	NET_ACCESSCTLCARD_TYPE_TEMPORARY_PERSON = 9,
	NET_ACCESSCTLCARD_TYPE_INVENTORY_PERSON = 10,
	NET_ACCESSCTLCARD_TYPE_INVENTORY_DIRECTOR = 11,
	NET_ACCESSCTLCARD_TYPE_SECURITY_GUARD = 12,
	NET_ACCESSCTLCARD_TYPE_SECURITYGUARD_DIRECTOR = 13,
	NET_ACCESSCTLCARD_TYPE_STORE_KEEPER = 14,
	NET_ACCESSCTLCARD_TYPE_STORE_DIRECTOR = 15,
	NET_ACCESSCTLCARD_TYPE_ESCORT_PERSON = 16,
	NET_ACCESSCTLCARD_TYPE_REPAIR_PERSON = 17,
	NET_ACCESSCTLCARD_TYPE_INSPECTOR = 18,
	NET_ACCESSCTLCARD_TYPE_SHENZHENLINK = 19,
	NET_ACCESSCTLCARD_TYPE_MOTHERCARD = 255
}
