// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_A_NET_EM_LATTICE_SCREEN_BACKGROUND_MODE

namespace BulkMaterialsForm.DH;

public enum EM_A_NET_EM_LATTICE_SCREEN_BACKGROUND_MODE
{
	NET_EM_LATTICE_SCREEN_BACKGROUND_MODE_UNKNOWN,
	NET_EM_LATTICE_SCREEN_BACKGROUND_MODE_A,
	NET_EM_LATTICE_SCREEN_BACKGROUND_MODE_B,
	NET_EM_LATTICE_SCREEN_BACKGROUND_MODE_C
}
