// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_ALARM_SCADA_DEV_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_ALARM_SCADA_DEV_TYPE
{
	UNKNOWN,
	LEAKAGE,
	THCONTROLLER,
	UPS,
	SWITCH,
	ELECTRICMETER,
	COMMERCIALPOWER,
	BATTERY,
	AIRCONDITION,
	ACCESS,
	SMOKINGSENSOR,
	INFRARED,
	CHEMICAL,
	PERIMETER,
	DOORMAGNETISM,
	DISTANCE,
	WINDSENSOR,
	LOCATION,
	ATMOSPHERE,
	SOLARPOWER
}
