// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_ALARM_CHASSISINTRUDED_DEV_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_ALARM_CHASSISINTRUDED_DEV_TYPE
{
	EM_ALARM_CHASSISINTRUDED_DEV_UNKNOWN,
	EM_ALARM_CHASSISINTRUDED_DEV_CONTROLLER,
	EM_ALARM_CHASSISINTRUDED_DEV_RS485EXPANSIONMODULE,
	EM_ALARM_CHASSISINTRUDED_DEV_MBUSEXPANSIONMODULE,
	EM_ALARM_CHASSISINTRUDED_DEV_KEYBOARD,
	EM_ALARM_CHASSISINTRUDED_DEV_SIREN
}
