// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_ALARM_BUS_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_ALARM_BUS_TYPE
{
	ALARM_BUS_DRIVER_CHECK = 1,
	ALARM_BUS_IMPORT_SITE,
	ALARM_BUS_EXPORT_SITE,
	ALARM_BUS_ABNORMAL,
	ALARM_BUS_DOOR_OPEN,
	ALARM_BUS_CUR_MILEAGE,
	ALARM_BUS_CUR_OIL,
	ALARM_BUS_LOW_OIL,
	ALARM_BUS_PASSENGER_CARD_CHECK,
	ALARM_BUS_VEHICLE_STANDING_OVER_TIME,
	ALARM_BUS_DRIVE_AFTER_WORK,
	ALARM_BUS_PAD_SHUTDOWN,
	ALARM_BUS_TIRED_DRIVE_CHECK,
	ALARM_BUS_STEAL_OIL,
	ALARM_BUS_CIRCUIT_SHIFT,
	ALARM_BUS_ROUTE_OVERTIME,
	ALARM_BUS_VEHICLE_CARRY_ALARM,
	ALARM_BUS_VEHICLE_PAULIN_ALARM,
	ALARM_BUS_VEHICLE_LIFT_ALARM,
	ALARM_BUS_FIRE_PRESSURE_ALARM,
	ALARM_BUS_ADD_OIL
}
