// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_BATTERY_TEMPER_STATE

namespace BulkMaterialsForm.DH;

public enum EM_BATTERY_TEMPER_STATE
{
	EM_BATTERY_TEMPER_STATE_UNKNOWN,
	EM_BATTERY_TEMPER_STATE_LOW_TEMPER,
	EM_BATTERY_TEMPER_STATE_NORMAL_TEMPER,
	EM_BATTERY_TEMPER_STATE_HIGH_TEMPER,
	EM_BATTERY_TEMPER_STATE_OVER_TEMPER,
	EM_BATTERY_TEMPER_STATE_ABNORMAL_TEMPER
}
