// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CFG_ACCESSCONTROLTYPE

namespace BulkMaterialsForm.DH;

public enum EM_CFG_ACCESSCONTROLTYPE
{
	NET_EM_CFG_ACCESSCONTROLTYPE_NULL,
	NET_EM_CFG_ACCESSCONTROLTYPE_AUTO,
	NET_EM_CFG_ACCESSCONTROLTYPE_OPEN,
	NET_EM_CFG_ACCESSCONTROLTYPE_CLOSE,
	NET_EM_CFG_ACCESSCONTROLTYPE_OPENALWAYS,
	NET_EM_CFG_ACCESSCONTROLTYPE_CLOSEALWAYS
}
