// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CATEGORY_NONMOTOR_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_CATEGORY_NONMOTOR_TYPE
{
	UNKNOWN,
	TRICYCLE,
	MOTORCYCLE,
	NON_MOTOR,
	BICYCLE,
	DUALTRIWHEELMOTORCYCLE,
	LIGHTMOTORCYCLE,
	EMBASSYMOTORCYCLE,
	MARGINALMOTORCYCLE,
	AREAOUTMOTORCYCLE,
	FOREIGNMOTORCYCLE,
	TRIALMOTORCYCLE,
	COACHMOTORCYCLE,
	PASSERBY,
	VANTRICYCLE,
	MANNEDCONVERTIBLETRICYCLE,
	NOMANNEDCONVERTIBLETRICYCLE
}
