// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CLOTHES_COLOR

namespace BulkMaterialsForm.DH;

public enum EM_CLOTHES_COLOR
{
	UNKNOWN,
	WHITE,
	ORANGE,
	PINK,
	BLACK,
	RED,
	YELLOW,
	GRAY,
	BLUE,
	GREEN,
	PURPLE,
	BROWN,
	EM_CLOTHES_COLOR_DARKORANGE,
	EM_CLOTHES_COLOR_OTHER,
	EM_CLOTHES_COLOR_SILVER,
	EM_CLOTHES_COLOR_DARKVIOLET,
	EM_CLOTHES_COLOR_MARRON,
	EM_CLOTHES_COLOR_DIMGRAY,
	EM_CLOTHES_COLOR_WHITESMOKE,
	EM_CLOTHES_COLOR_MISTYROSE,
	EM_CLOTHES_COLOR_TOMATO,
	EM_CLOTHES_COLOR_OLIVE,
	EM_CLOTHES_COLOR_GLOD,
	EM_CLOTHES_COLOR_DARKOLIVEGREEN,
	EM_CLOTHES_COLOR_CHARTREUSE,
	EM_CLOTHES_COLOR_GREENYELLOW,
	EM_CLOTHES_COLOR_FORESTGREEN,
	EM_CLOTHES_COLOR_SEAGREEN,
	EM_CLOTHES_COLOR_DEEPSKYBLUE,
	EM_CLOTHES_COLOR_CYAN,
	EM_CLOTHES_COLOR_LIGHTGREEN
}
