// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CFG_CROSSREGION_ALARMTYPE

namespace BulkMaterialsForm.DH;

public enum EM_CFG_CROSSREGION_ALARMTYPE
{
	EM_CFG_CROSSREGION_ALARMTYPE_UNKNOWN,
	EM_CFG_CROSSREGION_ALARMTYPE_ALARM,
	EM_CFG_CROSSREGION_ALARMTYPE_WARNING,
	EM_CFG_CROSSREGION_ALARMTYPE_SHIELD
}
