// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CAMERA_CHANNEL_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_CAMERA_CHANNEL_TYPE
{
	EM_CAMERA_CHANNEL_TYPE_UNKNOWN,
	EM_CAMERA_CHANNEL_TYPE_LOCAL,
	EM_CAMERA_CHANNEL_TYPE_REMOTE,
	EM_CAMERA_CHANNEL_TYPE_RESERVED32,
	EM_CAMERA_CHANNEL_TYPE_OUTPUT,
	EM_CAMERA_CHANNEL_TYPE_MATRIX,
	EM_CAMERA_CHANNEL_TYPE_COMPOSE,
	EM_CAMERA_CHANNEL_TYPE_CASCADE
}
