// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_COAXIAL_CONTROL_IO_TRIGGER_MODE

namespace BulkMaterialsForm.DH;

public enum EM_COAXIAL_CONTROL_IO_TRIGGER_MODE
{
	EM_COAXIAL_CONTROL_IO_TRIGGER_MODE_UNKNOWN,
	EM_COAXIAL_CONTROL_IO_TRIGGER_MODE_LINKAGE_TRIGGER,
	EM_COAXIAL_CONTROL_IO_TRIGGER_MODE_MANUAL_TRIGGER
}
