// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CUSTOM_EDUCATION_VOICE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_CUSTOM_EDUCATION_VOICE_TYPE
{
	EM_CUSTOM_EDUCATION_VOICE_TYPE_UNKNOWN = 0,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_LEAVE_SCHOOL_TIMEOUT = 1,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_ENTER_SCHOOL_TIMEOUT = 2,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_LEAVE_SCHOOL = 3,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_CARD_NOT_BIND = 4,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_BOARDER = 5,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_PARENT_CARD_REPORT_LOST = 6,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_ENTER_SCHOOL_OVERDUE = 7,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_PACKAGE_TO_PICKUP = 8,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_ASKFORLEAVE = 9,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_RETURN_SCHOOL_TIMEOUT_WHEN_ASKFORLEAVE = 10,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_INANDOUT_SCHOOL_TIMENOTUP_WHEN_ASKFORLEAVE = 11,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_REFUSE_LEAVE_SCHOOL_WHEN_ASKFORLEAVE = 12,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_REFUSE_ENTER_SCHOOL_WHEN_ASKFORLEAVE = 13,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_ASKFORLEAVE_IN_REVIEW = 14,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_ASKFORLEAVE_EXPIRED = 15,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_ASKFORLEAVE_APPROVED = 16,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_FORBID_LEAVE_SCHOOL_WITH_LEAVE_INVALID = 17,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_TIME_ISNOT_UP = 18,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_NOT_APPOINT = 19,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_NO_PASSAGE_IN_NONPERMIT_TIMESECTION = 20,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_INVALID_CARD = 21,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_ALREADY_APPOINTED = 22,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_ALLOW_BACK_SCHOOL = 23,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_GOODBYE = 24,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_ENTER_SCHOOL_NORMALLY = 25,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_REPEAT_LEAVE_SCHOOLL = 26,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_REPEAT_ENTER_SCHOOLL = 27,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_DAY_STUDENT = 28,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_WELCOME = 29,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_FACULTY = 30,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_TEACHER = 31,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_HELLO_TEACHER = 32,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_ALLOW_ACCESS = 33,
	EM_CUSTOM_EDUCATION_VOICE_TYPE_TTS_TEXT_VOICE_OUTPUT = 50
}
