// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CLOTHES_PATTERN

namespace BulkMaterialsForm.DH;

public enum EM_CLOTHES_PATTERN
{
	EM_CLOTHES_PATTERN_UNKNOWN,
	EM_CLOTHES_PATTERN_PURE,
	EM_CLOTHES_PATTERN_STRIPE,
	EM_CLOTHES_PATTERN_PATTERN,
	EM_CLOTHES_PATTERN_GAP,
	EM_CLOTHES_PATTERN_LATTICE,
	EM_CLOTHES_PATTERN_SPLITJOIN,
	EM_CLOTHES_PATTERN_FLORAL
}
