// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CLOUD_UPGRADER_STATE

namespace BulkMaterialsForm.DH;

public enum EM_CLOUD_UPGRADER_STATE
{
	EM_CLOUD_UPGRADER_STATE_UNKNOWN,
	EM_CLOUD_UPGRADER_STATE_NOUPGRADE,
	EM_CLOUD_UPGRADER_STATE_PREPARING,
	EM_CLOUD_UPGRADER_STATE_DOWNLOADING,
	EM_CLOUD_UPGRADER_STATE_DOWNLOADFAILED,
	EM_CLOUD_UPGRADER_STATE_UPGRADING,
	EM_CLOUD_UPGRADER_STATE_INVALID,
	EM_CLOUD_UPGRADER_STATE_FAILED,
	EM_CLOUD_UPGRADER_STATE_SUCCEEDED
}
