// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CLOUD_UPGRADER_CHECK_STATE

namespace BulkMaterialsForm.DH;

public enum EM_CLOUD_UPGRADER_CHECK_STATE
{
	EM_CLOUD_UPGRADER_CHECK_STATE_UNKNOWN,
	EM_CLOUD_UPGRADER_CHECK_STATE_NONE,
	EM_CLOUD_UPGRADER_CHECK_STATE_REGULAR,
	EM_CLOUD_UPGRADER_CHECK_STATE_EMERGENCY,
	EM_CLOUD_UPGRADER_CHECK_STATE_AUTOMATIC
}
