// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_COMPLIANTDETAIL_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_COMPLIANTDETAIL_TYPE
{
	EM_COMPLIANTDETAIL_UNKNOWN,
	EM_COMPLIANTDETAIL_MASK,
	EM_COMPLIANTDETAIL_HELMET,
	EM_COMPLIANTDETAIL_VEST,
	EM_COMPLIANTDETAIL_GLASSESS,
	EM_COMPLIANTDETAIL_COATCOLOR,
	EM_COMPLIANTDETAIL_TROUSESCOLOR
}
