// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CUSTOM_MEDICAL_VOICE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_CUSTOM_MEDICAL_VOICE_TYPE
{
	EM_CUSTOM_MEDICAL_VOICE_TYPE_UNKNOWN,
	EM_CUSTOM_MEDICAL_VOICE_TYPE_1,
	EM_CUSTOM_MEDICAL_VOICE_TYPE_2,
	EM_CUSTOM_MEDICAL_VOICE_TYPE_3,
	EM_CUSTOM_MEDICAL_VOICE_TYPE_4,
	EM_CUSTOM_MEDICAL_VOICE_TYPE_5,
	EM_CUSTOM_MEDICAL_VOICE_TYPE_6,
	EM_CUSTOM_MEDICAL_VOICE_TYPE_7
}
