// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CERTIFICATE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_CERTIFICATE_TYPE
{
	CERTIFICATE_TYPE_UNKNOWN,
	CERTIFICATE_TYPE_IC,
	CERTIFICATE_TYPE_PASSPORT,
	CERTIFICATE_TYPE_OUTERGUARD,
	CERTIFICATE_TYPE_STUDENT,
	CERTIFICATE_TYPE_POLICE,
	CERTIFICATE_TYPE_LAWYER
}
