// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_CLOUD_UPGRADER_PACKAGE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_CLOUD_UPGRADER_PACKAGE_TYPE
{
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_UNKNOWN,
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_ALL,
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_PTZ,
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_WEB,
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_LOGO,
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_CUSTOM,
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_GUI,
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_PD,
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_DATA,
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_PTZ_POWER,
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_PTZ_LIGHT,
	EM_CLOUD_UPGRADER_PACKAGE_TYPE_PTZ_HEATER
}
