// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_DIALDETECT_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_DIALDETECT_TYPE
{
	EM_DIALDETECT_TYPE_UNKNOWN,
	EM_DIALDETECT_TYPE_PLATEN,
	EM_DIALDETECT_TYPE_KNIFE,
	EM_DIALDETECT_TYPE_POINTERMETER,
	EM_DIALDETECT_TYPE_OILMETER,
	EM_DIALDETECT_TYPE_LED,
	EM_DIALDETECT_TYPE_LCD,
	EM_DIALDETECT_TYPE_LIGHT,
	EM_DIALDETECT_TYPE_SWITCH,
	EM_DIALDETECT_TYPE_PESPIRATOR,
	EM_DIALDETECT_TYPE_CHARLNDICTOR,
	EM_DIALDETECT_TYPE_POINTERLNDICTOR,
	EM_DIALDETECT_TYPE_OILLEVEL,
	EM_DIALDETECT_TYPE_DIALSWTICH
}
