// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_DEVCAP_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_DEVCAP_TYPE
{
	DEV_CAP_SEQPOWER = 1,
	ENCODE_CFG_CAPS = 2,
	VIDEOIN_FISHEYE_CAPS = 3,
	COMPOSITE_CAPS = 4,
	VIDEO_DETECT_CAPS = 5,
	THERMO_GRAPHY_CAPS = 6,
	RADIOMETRY_CAPS = 7,
	POS_CAPS = 8,
	USER_MNG_CAPS = 9,
	MEDIAMANAGER_CAPS = 10,
	VIDEO_MOSAIC_CAPS = 11,
	SNAP_CFG_CAPS = 12,
	VIDEOIN_CAPS = 13,
	FACE_BOARD_CAPS = 14,
	EXTERNALSENSOR_CAPS = 15,
	VIDEO_IMAGECONTROL_CAPS = 16,
	VIDEOIN_EXPOSURE_CAPS = 17,
	VIDEOIN_DENOISE_CAPS = 18,
	VIDEOIN_BACKLIGHT_CAPS = 19,
	VIDEOIN_WHITEBALANCE_CAPS = 20,
	VIDEOIN_DAYNIGHT_CAPS = 21,
	VIDEOIN_ZOOM_CAPS = 22,
	VIDEOIN_FOCUS_CAPS = 23,
	VIDEOIN_SHARPNESS_CAPS = 24,
	VIDEOIN_COLOR_CAPS = 25,
	GET_MASTERSLAVEGROUP_CAPS = 26,
	FACERECOGNITIONSE_CAPS = 27,
	STORAGE_CAPS = 28,
	VIDEOIN_RAWFRAME_CAPS = 29,
	COAXIAL_CONTROL_IO_CAPS = 30,
	FACEINFO_CAPS = 31,
	ACCESSCONTROL_CAPS = 32,
	REMOTE_SPEAK_CAPS = 56,
	IXRAY_PACKAGE_MANAGER_CAPS = 65
}
