// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_DEFENCE_AREA_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_DEFENCE_AREA_TYPE
{
	EM_DEFENCE_AREA_TYPE_UNKNOWN,
	EM_DEFENCE_AREA_TYPE_INTIME,
	EM_DEFENCE_AREA_TYPE_DELAY,
	EM_DEFENCE_AREA_TYPE_DELAY2,
	EM_DEFENCE_AREA_TYPE_FOLLOW,
	EM_DEFENCE_AREA_TYPE_EXITEND,
	EM_DEFENCE_AREA_TYPE_FULLDAY,
	EM_DEFENCE_AREA_TYPE_FIRE,
	EM_DEFENCE_AREA_TYPE_PANIC,
	EM_DEFENCE_AREA_TYPE_ROBBERY,
	EM_DEFENCE_AREA_TYPE_MEDICAL,
	EM_DEFENCE_AREA_TYPE_KEY
}
