// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_EXPORT_FACEDB_ERRORCODE

namespace BulkMaterialsForm.DH;

public enum EM_EXPORT_FACEDB_ERRORCODE
{
	EM_EXPORT_FACEDB_REQUEST_SUCCESS = 1,
	EM_EXPORT_FACEDB_NO_AUTHORITY = 2,
	EM_EXPORT_FACEDB_NO_THIS_FILE = 3,
	EM_EXPORT_FACEDB_EXPORT_END = 4,
	EM_EXPORT_FACEDB_EXPORTING = 5,
	EM_EXPORT_FACEDB_FILE_READY = 8,
	EM_EXPORT_FACEDB_FILE_FAILED = 9,
	EM_EXPORT_FACEDB_WAIT_FILE = 10,
	EM_EXPORT_FACEDB_SYSTEM_BUSY = 11,
	EM_EXPORT_FACEDB_NO_PASSWORD = 12
}
