// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_EVENT_DETECT_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_EVENT_DETECT_TYPE
{
	EM_EVENT_DETECT_TYPE_UNKNOWN = -1,
	EM_EVENT_DETECT_TYPE_LESS_OR_EQUAL,
	EM_EVENT_DETECT_TYPE_GREATER_OR_EQUAL,
	EM_EVENT_DETECT_TYPE_EQUAL,
	EM_EVENT_DETECT_TYPE_NOEQUAL,
	EM_EVENT_DETECT_TYPE_CHANGE,
	EM_EVENT_DETECT_TYPE_GREATER,
	EM_EVENT_DETECT_TYPE_LESS,
	EM_EVENT_DETECT_TYPE_IN_INTERVAL,
	EM_EVENT_DETECT_TYPE_OUT_INTERVAL
}
