// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_EVENT_WORKCLOTHES_RULE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_EVENT_WORKCLOTHES_RULE_TYPE
{
	EM_EVENT_WORKCLOTHES_RULE_UNKNWON,
	EM_EVENT_WORKCLOTHES_RULE_HELMET,
	EM_EVENT_WORKCLOTHES_RULE_CLOTHES,
	EM_EVENT_WORKCLOTHES_RULE_PANTS,
	EM_EVENT_WORKCLOTHES_RULE_PROTECTIVESUIT,
	EM_EVENT_WORKCLOTHES_RULE_SHOESCOVER,
	EM_EVENT_WORKCLOTHES_RULE_SAFETYROPE,
	EM_EVENT_WORKCLOTHES_RULE_NORMALHAT,
	EM_EVENT_WORKCLOTHES_RULE_MASK,
	EM_EVENT_WORKCLOTHES_RULE_APRON,
	EM_EVENT_WORKCLOTHES_RULE_GLOVE,
	EM_EVENT_WORKCLOTHES_RULE_BOOT,
	EM_EVENT_WORKCLOTHES_RULE_NOHAT,
	EM_EVENT_WORKCLOTHES_RULE_TYPE_PROHLMET,
	EM_EVENT_WORKCLOTHES_RULE_FIREPROOFCLOTHES
}
