// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_ENCLOSURE_TYPE_EX

namespace BulkMaterialsForm.DH;

public enum EM_ENCLOSURE_TYPE_EX
{
	EM_ENCLOSURE_TYPE_EX_UNKNOWN,
	EM_ENCLOSURE_TYPE_EX_LIMITSPEED,
	EM_ENCLOSURE_TYPE_EX_DRIVEALLOW,
	EM_ENCLOSURE_TYPE_EX_FORBIDDRIVE,
	EM_ENCLOSURE_TYPE_EX_LOADGOODS,
	EM_ENCLOSURE_TYPE_EX_UPLOADGOODS
}
