// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_FACEDB_ERRCODE

namespace BulkMaterialsForm.DH;

public enum EM_FACEDB_ERRCODE
{
	EM_FACEDB_ERRCODE_UNKNOWN = -1,
	EM_FACEDB_ERRCODE_SUCCESS = 0,
	EM_FACEDB_ERRCODE_CONNECT_FAIL = 2,
	EM_FACEDB_ERRCODE_LOGIN_FAIL = 3,
	EM_FACEDB_ERRCODE_RECV_TIMEOUT = 4,
	EM_FACEDB_ERRCODE_STRING_NULL = 5,
	EM_FACEDB_ERRCODE_FILE_DIRECTORY_NOT_EXIST = 6,
	EM_FACEDB_ERRCODE_STORAGE_FAIL = 7
}
