// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_FILE_QUERY_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_FILE_QUERY_TYPE
{
	TRAFFICCAR = 0,
	ATM = 1,
	ATMTXN = 2,
	FACE = 3,
	FILE = 4,
	TRAFFICCAR_EX = 5,
	FACE_DETECTION = 6,
	IVS_EVENT = 7,
	ANALYSE_OBJECT = 8,
	MPT_RECORD_FILE = 9,
	XRAY_DETECTION = 10,
	HUMAN_TRAIT = 11,
	NONMOTOR = 12,
	DOORCONTROL_RECORD = 13,
	FACEBODY_DETECT = 14,
	FACEBODY_ANALYSE = 15,
	FILE_EX = 16,
	SNAPSHOT_WITH_MARK = 17,
	ANATOMY_TEMP_DETECT = 18,
	ILLEGAL_TRAFFIC = 19,
	SMOKE_FIRE = 20,
	FIRE_CONTROL_MONITOR = 21,
	FIRE_LANE_DETECTION = 22,
	NONMOTOR_ENTRYING = 23,
	WORK_CLOTHES_DETECTION = 24,
	INTELLIGENT_CITY_MANAGER = 25,
	EM_FILE_QUERY_EXAM = 33
}
