// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_FAILCODE

namespace BulkMaterialsForm.DH;

public enum EM_FAILCODE
{
	NOERROR,
	UNKNOWN,
	INVALID_PARAM,
	INVALID_PASSWORD,
	INVALID_FP,
	INVALID_FACE,
	INVALID_CARD,
	INVALID_USER,
	FAILED_GET_SUBSERVICE,
	FAILED_GET_METHOD,
	FAILED_GET_SUBCAPS,
	ERROR_INSERT_LIMIT,
	ERROR_MAX_INSERT_RATE,
	FAILED_ERASE_FP,
	FAILED_ERASE_FACE,
	FAILED_ERASE_CARD,
	NO_RECORD,
	NOMORE_RECORD,
	RECORD_ALREADY_EXISTS,
	MAX_FP_PERUSER,
	MAX_CARD_PERUSER,
	EXCEED_MAX_PHOTOSIZE,
	INVALID_USERID,
	EXTRACTFEATURE_FAIL,
	PHOTO_EXIST,
	PHOTO_OVERFLOW,
	INVALID_PHOTO_FORMAT,
	EXCEED_ADMINISTRATOR_LIMIT
}
