// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_FIELTRANSMIT_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_FIELTRANSMIT_TYPE
{
	UPGRADEFILETRANS_START = 0,
	UPGRADEFILETRANS_SEND = 1,
	UPGRADEFILETRANS_STOP = 2,
	BLACKWHITETRANS_START = 3,
	BLACKWHITETRANS_SEND = 4,
	BLACKWHITETRANS_STOP = 5,
	BLACKWHITE_LOAD = 6,
	BLACKWHITE_LOAD_STOP = 7,
	FILETRANS_STOP = 43,
	FILETRANS_BURN = 44
}
