// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_GLOBAL_LANES_LINE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_GLOBAL_LANES_LINE_TYPE
{
	EM_GLOBAL_LANES_LINE_TYPE_UNKNOWN,
	EM_GLOBAL_LANES_LINE_TYPE_WHITESOLID,
	EM_GLOBAL_LANES_LINE_TYPE_WHITEDOTTED,
	EM_GLOBAL_LANES_LINE_TYPE_YELLOW,
	EM_GLOBAL_LANES_LINE_TYPE_UPSOLIDDOWNDOTTED,
	EM_GLOBAL_LANES_LINE_TYPE_UPDOTTEDDOWNSOLID
}
