// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_GREENCNHEALTH_STATUS

namespace BulkMaterialsForm.DH;

public enum EM_GREENCNHEALTH_STATUS
{
	EM_GREENCNHEALTH_STATUS_UNKNOWN,
	EM_GREENCNHEALTH_STATUS_GREEN,
	EM_GREENCNHEALTH_STATUS_YELLOW,
	EM_GREENCNHEALTH_STATUS_RED,
	EM_GREENCNHEALTH_STATUS_INVALID
}
