// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_HUMAN_HAIR_STYLE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_HUMAN_HAIR_STYLE_TYPE
{
	EM_HUMAN_HAIR_STYLE_TYPE_UNKNOWN,
	EM_HUMAN_HAIR_STYLE_TYPE_LONG,
	EM_HUMAN_HAIR_STYLE_TYPE_SHORT,
	EM_HUMAN_HAIR_STYLE_TYPE_PONYTAIL,
	EM_HUMAN_HAIR_STYLE_TYPE_UPDO,
	EM_HUMAN_HAIR_STYLE_TYPE_HEAD_COVERED
}
