// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_INSTRUMENT_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_INSTRUMENT_TYPE
{
	EM_INSTRUMENT_TYPE_UNKNOWN,
	EM_INSTRUMENT_TYPE_STATE,
	EM_INSTRUMENT_TYPE_STATEMATCH,
	EM_INSTRUMENT_TYPE_METER,
	EM_INSTRUMENT_TYPE_CHAR,
	EM_INSTRUMENT_TYPE_OIL,
	EM_INSTRUMENT_TYPE_SWIIDEN,
	EM_INSTRUMENT_TYPE_LIGHT,
	EM_INSTRUMENT_TYPE_SWITCH,
	EM_INSTRUMENT_TYPE_APPEARANCE,
	EM_INSTRUMENT_TYPE_LEVELGAUGE
}
