// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_IMPORT_FACEDB_STATE

namespace BulkMaterialsForm.DH;

public enum EM_IMPORT_FACEDB_STATE
{
	EM_IMPORT_FACEDB_UNKNOWN,
	EM_IMPORT_FACEDB_ONGING,
	EM_IMPORT_FACEDB_END,
	EM_IMPORT_FACEDB_BUSY,
	EM_IMPORT_FACEDB_DATAERROR,
	EM_IMPORT_FACEDB_INVALID,
	EM_IMPORT_FACEDB_SYNC_SUCCESS,
	EM_IMPORT_FACEDB_SYNC_FALIED,
	EM_IMPORT_FACEDB_DBFULL,
	EM_IMPORT_FACEDB_SDFULL,
	EM_IMPORT_FACEDB_CIPHER_ERROR,
	EM_IMPORT_FACEDB_SEND_FAIL,
	EM_IMPORT_FACEDB_UPLOAD_FAIL,
	EM_IMPORT_FACEDB_UPLOAD_NO_PERMISSION
}
