// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_IMAGE_TYPE_EX2

namespace BulkMaterialsForm.DH;

public enum EM_IMAGE_TYPE_EX2
{
	EM_IMAGE_TYPE_UNKNOWN,
	EM_IMAGE_TYPE_SCENE_IMAGE,
	EM_IMAGE_TYPE_GLOBAL_SCENE,
	EM_IMAGE_TYPE_THUM_IMAGE,
	EM_IMAGE_TYPE_FACE_SCENE_IMAGE,
	EM_IMAGE_TYPE_FACE_IMAGE,
	EM_IMAGE_TYPE_HUMAN_IMAGE,
	EM_IMAGE_TYPE_ALONG_WITH_FACE_HUMAN_IMAGE,
	EM_IMAGE_TYPE_ALONG_WITH_FACE_HUMAN_SCENE_IMAGE,
	EM_IMAGE_TYPE_PARKING_IMAGE,
	EM_IMAGE_TYPE_BINARIZED_PLATE,
	EM_IMAGE_TYPE_DEPOSIT_IMAGE_INFO,
	EM_IMAGE_TYPE_IMAGE_INFO
}
