// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_NET_VEHICLE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_NET_VEHICLE_TYPE
{
	UNKNOWN,
	MOTOR,
	NON_MOTOR,
	BUS,
	BICYCLE,
	MOTORCYCLE,
	UNLICENSEDMOTOR,
	LARGECAR,
	MICROCAR,
	EMBASSYCAR,
	MARGINALCAR,
	AREAOUTCAR,
	FOREIGNCAR,
	DUALTRIWHEELMOTORCYCLE,
	LIGHTMOTORCYCLE,
	EMBASSYMOTORCYCLE,
	MARGINALMOTORCYCLE,
	AREAOUTMOTORCYCLE,
	FOREIGNMOTORCYCLE,
	FARMTRANSMITCAR,
	TRACTOR,
	TRAILER,
	COACHCAR,
	COACHMOTORCYCLE,
	TRIALCAR,
	TRIALMOTORCYCLE,
	TEMPORARYENTRYCAR,
	TEMPORARYENTRYMOTORCYCLE,
	TEMPORARYSTEERCAR,
	PASSENGERCAR,
	LARGETRUCK,
	MIDTRUCK,
	SALOONCAR,
	MICROBUS,
	MICROTRUCK,
	TRICYCLE,
	PASSERBY
}
