// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_NET_BURN_STATE

namespace BulkMaterialsForm.DH;

public enum EM_NET_BURN_STATE
{
	BURN_STATE_STOP,
	BURN_STATE_STOPING,
	BURN_STATE_INIT,
	BURN_STATE_BURNING,
	BURN_STATE_PAUSE,
	BURN_STATE_CHANGE_DISK,
	BURN_STATE_PREPARE_EXTRA_FILE,
	BURN_STATE_WAIT_EXTRA_FILE,
	BURN_STATE_UPLOAD_FILE_START,
	BURN_STATE_CHECKING_DISK,
	BURN_STATE_DISK_READY
}
