// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_NONMOTOR_FEATURE

namespace BulkMaterialsForm.DH;

public enum EM_NONMOTOR_FEATURE
{
	EM_NONMOTOR_FEATURE_UNKNOWN,
	EM_NONMOTOR_FEATURE_HELMET,
	EM_NONMOTOR_FEATURE_NUMOFCYCLING,
	EM_NONMOTOR_FEATURE_NONMOTORCOLOR,
	EM_NONMOTOR_FEATURE_SEX,
	EM_NONMOTOR_FEATURE_AGE,
	EM_NONMOTOR_FEATURE_HAT,
	EM_NONMOTOR_FEATURE_BAG,
	EM_NONMOTOR_FEATURE_CARRIERBAG,
	EM_NONMOTOR_FEATURE_UMBRELLA,
	EM_NONMOTOR_FEATURE_UPPERBODYCOLOR,
	EM_NONMOTOR_FEATURE_LOWERBODYCOLOR,
	EM_NONMOTOR_FEATURE_UPCLOTHES,
	EM_NONMOTOR_FEATURE_DOWNCLOTHES,
	EM_NONMOTOR_FEATURE_CATEGORY
}
