// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_NONMOTOR_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_NONMOTOR_TYPE
{
	EM_NONMOTOR_TYPE_UNKNOWN,
	EM_NONMOTOR_TYPE_BICYCLE,
	EM_NONMOTOR_TYPE_VANTRICYCLE,
	EM_NONMOTOR_TYPE_MOTORBIKE,
	EM_NONMOTOR_TYPE_MANNED_CONVERTIBLE_TRICYCLE,
	EM_NONMOTOR_TYPE_NO_MANNED_CONVERTIBLE_TRICYCLE
}
