// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_NET_RECORD_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_NET_RECORD_TYPE
{
	UNKNOWN,
	TRAFFICWHITELIST,
	TRAFFICBLACKLIST,
	BURN_CASE,
	ACCESSCTLCARD,
	ACCESSCTLPWD,
	ACCESSCTLCARDREC,
	ACCESSCTLHOLIDAY,
	TRAFFICFLOW_STATE,
	VIDEOTALKLOG,
	REGISTERUSERSTATE,
	VIDEOTALKCONTACT,
	ANNOUNCEMENT,
	ALARMRECORD,
	COMMODITYNOTICE,
	HEALTHCARENOTICE,
	ACCESSCTLCARDREC_EX,
	GPS_LOCATION,
	RESIDENT,
	SENSORRECORD,
	ACCESSQRCODE,
	ELECTRONICSTAG,
	ACCESS_BLUETOOTH,
	ACCESS_ALARMRECORD
}
