// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_NET_SPLIT_OPERATE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_NET_SPLIT_OPERATE_TYPE
{
	SET_BACKGROUND,
	GET_BACKGROUND,
	SET_PREPULLSRC,
	SET_HIGHLIGHT,
	SET_ZORDER,
	SET_TOUR,
	GET_TOUR_STATUS,
	GET_SCENE,
	OPEN_WINDOWS,
	SET_WORK_MODE,
	GET_PLAYER,
	SET_WM_WORK_MODE,
	GET_WORK_MODE,
	CLOSE_WINDOWS,
	SET_FISH_EYE_PARAM,
	SET_CORRIDOR_MODE,
	GET_CORRIDOR_MODE,
	SET_VOLUME_COLUMN,
	GET_VOLUME_COLUMN,
	SET_WM_BACKGROUND,
	GET_WM_BACKGROUND
}
