// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_NET_PLATE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_NET_PLATE_TYPE
{
	UNKNOWN,
	NORMAL,
	YELLOW,
	DOUBLEYELLOW,
	POLICE,
	NET_PLATE_TYPE_WJ,
	NET_PLATE_TYPE_OUTERGUARD,
	NET_PLATE_TYPE_DOUBLEOUTERGUARD,
	SAR,
	TRAINNING,
	PERSONAL,
	AGRI,
	EMBASSY,
	MOTO,
	TRACTOR,
	OFFICIALCAR,
	PERSONALCAR,
	WARCAR,
	OTHER,
	CIVILAVIATION,
	BLACK,
	PURENEWENERGYMICROCAR,
	MIXEDNEWENERGYMICROCAR,
	PURENEWENERGYLARGECAR,
	MIXEDNEWENERGYLARGECAR
}
