// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_NEWUPCLOTHES_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_NEWUPCLOTHES_TYPE
{
	EM_NEWUPCLOTHES_TYPE_UNKNOWN,
	EM_NEWUPCLOTHES_TYPE_LONG_SLEEVE,
	EM_NEWUPCLOTHES_TYPE_SHORT_SLEEVE,
	EM_NEWUPCLOTHES_TYPE_LONGCOAT,
	EM_NEWUPCLOTHES_TYPE_JACKET_AND_JEANS,
	EM_NEWUPCLOTHES_TYPE_TSHIRT,
	EM_NEWUPCLOTHES_TYPE_SPORTWEAR,
	EM_NEWUPCLOTHES_TYPE_DOWNJACKETS,
	EM_NEWUPCLOTHES_TYPE_SHIRT,
	EM_NEWUPCLOTHES_TYPE_DRESS,
	EM_NEWUPCLOTHES_TYPE_SUIT,
	EM_NEWUPCLOTHES_TYPE_SWEATER,
	EM_NEWUPCLOTHES_TYPE_SLEEVELESS,
	EM_NEWUPCLOTHES_TYPE_VEST
}
