// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_OBJECT_NONMOTORANGLE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_OBJECT_NONMOTORANGLE_TYPE
{
	EM_OBJECT_NONMOTORANGLE_TYPE_UNKNOWN,
	EM_OBJECT_NONMOTORANGLE_TYPE_FRONT,
	EM_OBJECT_NONMOTORANGLE_TYPE_SIDE,
	EM_OBJECT_NONMOTORANGLE_TYPE_BEHIND
}
