// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_OBJECT_STORAGEBOX_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_OBJECT_STORAGEBOX_TYPE
{
	EM_OBJECT_STORAGEBOX_UNKNOWN,
	EM_OBJECT_STORAGEBOX_NO,
	EM_OBJECT_STORAGEBOX_OWNBOX,
	EM_OBJECT_STORAGEBOX_SELFPACK,
	EM_OBJECT_STORAGEBOX_ALL
}
