// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_PASS_MODE

namespace BulkMaterialsForm.DH;

public enum EM_PASS_MODE
{
	UNKNOWN = -1,
	IN_AUTHORIZATION_OUT_AUTHORIZATION,
	IN_AUTHORIZATION_OUT_FREE,
	IN_AUTHORIZATION_OUT_FORBID,
	IN_FREE_OUT_AUTHORIZATION,
	IN_FREE_OUT_FREE,
	IN_FREE_OUT_FORBID,
	IN_FORBID_OUT_AUTHORIZATION,
	IN_FORBID_OUT_FREE,
	IN_FORBID_OUT_FORBID
}
