// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_PLATE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_PLATE_TYPE
{
	EM_PLATE_OTHER,
	EM_PLATE_BIG_CAR,
	EM_PLATE_SMALL_CAR,
	EM_PLATE_EMBASSY_CAR,
	EM_PLATE_CONSULATE_CAR,
	EM_PLATE_ABROAD_CAR,
	EM_PLATE_FOREIGN_CAR,
	EM_PLATE_LOW_SPEED_CAR,
	EM_PLATE_COACH_CAR,
	EM_PLATE_MOTORCYCLE,
	EM_PLATE_NEW_POWER_CAR,
	EM_PLATE_POLICE_CAR,
	EM_PLATE_HONGKONG_MACAO_CAR,
	EM_PLATE_WJPOLICE_CAR,
	EM_PLATE_OUTERGUARD_CAR,
	EM_PLATE_TEMPORARY_LICENSE_FOR_NON_MOTOR_VEHICLES,
	EM_PLATE_OFFICIAL_LICENSE_PLATE_FOR_NON_MOTOR_VEHICLE
}
