// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_POWERFAULT_EVENT_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_POWERFAULT_EVENT_TYPE
{
	EM_POWERFAULT_EVENT_UNKNOWN = -1,
	EM_POWERFAULT_EVENT_LOST,
	EM_POWERFAULT_EVENT_LOST_ADAPTER,
	EM_POWERFAULT_EVENT_LOW_BATTERY,
	EM_POWERFAULT_EVENT_LOW_ADAPTER,
	EM_POWERFAULT_EVENT_LOW_ADAPTER_LOST_BATTERY,
	EM_POWERFAULT_EVENT_LESS_ADAPTER_LOW_BATTERY,
	EM_POWERFAULT_EVENT_LESS_ADAPTER_LOST_BATTERY,
	EM_POWERFAULT_EVENT_LOST_ADAPTER_LOST_BATTERY,
	EM_POWERFAULT_EVENT_LOW_ADAPTER_LOW_BATTERY
}
