// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_PLATE_COLOR_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_PLATE_COLOR_TYPE
{
	EM_PLATE_COLOR_UNKNOWN,
	EM_PLATE_COLOR_OTHER,
	EM_PLATE_COLOR_BLUE,
	EM_PLATE_COLOR_YELLOW,
	EM_PLATE_COLOR_WHITE,
	EM_PLATE_COLOR_BLACK,
	EM_PLATE_COLOR_RED,
	EM_PLATE_COLOR_GREEN,
	EM_PLATE_COLOR_SHADOW_GREEN,
	EM_PLATE_COLOR_YELLOW_GREEN,
	EM_PLATE_COLOR_YELLOW_BOTTOM_BLACK_TEXT,
	EM_PLATE_COLOR_BLUE_BOTTOM_WHITE_TEXT,
	EM_PLATE_COLOR_BLACK_BOTTOM_WHITE_TEXT
}
