// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_QUERY_DEV_INFO

namespace BulkMaterialsForm.DH;

public enum EM_QUERY_DEV_INFO
{
	STORAGE_NAMES = 1,
	STORAGE_INFOS = 2,
	RECENCY_JNNCTION_CAR_INFO = 3,
	LANES_STATE = 4,
	FISHEYE_WININFO = 5,
	REMOTE_DEVICE_INFO = 6,
	SYSTEM_INFO = 7,
	REG_DEVICE_NET_INFO = 8,
	THERMO_GRAPHY_PRESET = 9,
	THERMO_GRAPHY_OPTREGION = 10,
	THERMO_GRAPHY_EXTSYSINFO = 11,
	RADIOMETRY_POINT_TEMPER = 12,
	RADIOMETRY_TEMPER = 13,
	GET_CAMERA_STATE = 14,
	GET_REMOTE_CHANNEL_AUDIO_ENCODE = 15,
	GET_COMM_PORT_INFO = 16,
	GET_LINKCHANNELS = 17,
	GET_VIDEOOUTPUTCHANNELS = 18,
	GET_VIDEOINFO = 19,
	GET_ALLLINKCHANNELS = 20,
	VIDEOCHANNELSINFO = 21,
	TRAFFICRADAR_VERSION = 22,
	WORKGROUP_NAMES = 23,
	WORKGROUP_INFO = 24,
	WLAN_ACCESSPOINT = 25,
	GPS_INFO = 26,
	IVS_REMOTE_DEVICE_INFO = 27,
	SMART_SWITCH_INFO = 28,
	UPGRADE_STATE = 29,
	VIDEO_ENCODE_CAPS = 30,
	AUDIO_ENCODE_CAPS = 31,
	AUDIO_IN_CAPS = 32,
	SMART_ENCODE_CAPS = 33,
	HARDDISK_TEMPERATURE = 34,
	RAWFRAMEDATA = 35,
	GETSPLICEDATA = 36,
	AUDIO_DECODE_CAPS = 37,
	DEVICE_ID = 38,
	REMOTE_DEVICE_CAPS = 39,
	TRAFFIC_SNAP_RADAR = 40,
	TRAFFIC_SNAP_STROBE = 41,
	GET_ALL_PARKING_SPACE_STATUS = 50,
	TRAFFIC_RADAR_GET_OBJECT = 53,
	PTZBASE_GET_HFOV_VALUE = 57
}
