// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_RADAR_OBJECTTYPE

namespace BulkMaterialsForm.DH;

public enum EM_RADAR_OBJECTTYPE
{
	EM_RADAR_OBJECTTYPE_UNKNOWN,
	EM_RADAR_OBJECTTYPE_PERSON,
	EM_RADAR_OBJECTTYPE_VEHICLE,
	EM_RADAR_OBJECTTYPE_TREE,
	EM_RADAR_OBJECTTYPE_BUILIDING,
	EM_RADAR_OBJECTTYPE_SCREEN,
	EM_RADAR_OBJECTTYPE_ANIMAL,
	EM_RADAR_OBJECTTYPE_BIG_SHIP,
	EM_RADAR_OBJECTTYPE_MID_SHIP,
	EM_RADAR_OBJECTTYPE_SMALL_SHIP,
	EM_RADAR_OBJECTTYPE_STATIONARY_TARGET_TYPE
}
