// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_REASON_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_REASON_TYPE
{
	EM_REASON_TYPE_UNKNOWN,
	EM_REASON_TYPE_OVERNUMBER,
	EM_REASON_TYPE_FULLSTORAGE,
	EM_REASON_TYPE_TOOLARGE_FILE,
	EM_REASON_TYPE_INVALID_FILETYPE,
	EM_REASON_TYPE_UNAUTH_UPLOAD,
	EM_REASON_TYPE_EXCEPTION_NAME,
	EM_REASON_TYPE_TOOLONG_NAME,
	EM_REASON_TYPE_EXIST_NAME
}
