// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_RESPIRATOR_STATE

namespace BulkMaterialsForm.DH;

public enum EM_RESPIRATOR_STATE
{
	EM_RESPIRATOR_STATE_UNKNOWN,
	EM_RESPIRATOR_STATE_NORMAL,
	EM_RESPIRATOR_STATE_SILICA_GEL_COLOR_CHANGE,
	EM_RESPIRATOR_STATE_SILICA_GEL_BARREL_BROKEN,
	EM_RESPIRATOR_STATE_ABNORMAL_OIL_LEVEL
}
