// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_RCEMERGENCY_CALL_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_RCEMERGENCY_CALL_TYPE
{
	EM_RCEMERGENCY_CALL_UNKNOWN,
	EM_RCEMERGENCY_CALL_FIRE,
	EM_RCEMERGENCY_CALL_DURESS,
	EM_RCEMERGENCY_CALL_ROBBER,
	EM_RCEMERGENCY_CALL_MEDICAL,
	EM_RCEMERGENCY_CALL_EMERGENCY,
	EM_RCEMERGENCY_CALL_PANIC
}
