// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_RENT_STATE

namespace BulkMaterialsForm.DH;

public enum EM_RENT_STATE
{
	EM_RENT_STATE_UNKNOWN,
	EM_RENT_STATE_NORMAL_PAYMENT,
	EM_RENT_STATE_0_TO_3_MONTHS_IN_ARREARS,
	EM_RENT_STATE_3_TO_6_MONTHS_IN_ARREARS,
	EM_RENT_STATE_6_TO_12_MONTHS_IN_ARREARS,
	EM_RENT_STATE_MORE_THAN_12_MONTHS_IN_ARREARS,
	EM_RENT_STATE_TEMPORARY_VISITOR
}
