// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_RECORD_BACKUP_FAIL_REASON

namespace BulkMaterialsForm.DH;

public enum EM_RECORD_BACKUP_FAIL_REASON
{
	EM_RECORD_BACKUP_FAIL_REASON_UNKNOW,
	EM_RECORD_BACKUP_FAIL_REASON_LOGIN_FAIL,
	EM_RECORD_BACKUP_FAIL_REASON_NO_FILES,
	EM_RECORD_BACKUP_FAIL_REASON_DOWNLOAD_NET_ERROR,
	EM_RECORD_BACKUP_FAIL_REASON_UNKNOW_ERROR
}
