// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_RADAR_GETCAPS_RADAR_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_RADAR_GETCAPS_RADAR_TYPE
{
	EM_RADAR_GETCAPS_RADAR_TYPE_UNKNOWN,
	EM_RADAR_GETCAPS_RADAR_TYPE1,
	EM_RADAR_GETCAPS_RADAR_TYPE2,
	EM_RADAR_GETCAPS_RADAR_TYPE3,
	EM_RADAR_GETCAPS_RADAR_TYPE4,
	EM_RADAR_GETCAPS_RADAR_TYPE5
}
