// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_STORAGEPOINT_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_STORAGEPOINT_TYPE
{
	EM_STORAGE_TIMINGRECORD,
	EM_STORAGE_MANUALRECORD,
	EM_STORAGE_VIDEODETECTRECORD,
	EM_STORAGE_ALARMRECORD,
	EM_STORAGE_CARDRECORD,
	EM_STORAGE_EVENTRECORD,
	EM_STORAGE_TIMINGSNAPSHOT,
	EM_STORAGE_MANUALSNAPSHOT,
	EM_STORAGE_VIDEODETECTSNAPSHOT,
	EM_STORAGE_ALARMSNAPSHOT,
	EM_STORAGE_CARDSNAPSHOT,
	EM_STORAGE_EVENTSNAPSHOT,
	EM_STORAGE_TIMINGEXTRA1RECORD
}
