// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_SUPPORT_LIFT_CONTROL_TYPES

namespace BulkMaterialsForm.DH;

public enum EM_SUPPORT_LIFT_CONTROL_TYPES
{
	EM_SUPPORT_LIFT_CONTROL_TYPES_UNKNOWN,
	EM_SUPPORT_LIFT_CONTROL_TYPES_LOCAL485,
	EM_SUPPORT_LIFT_CONTROL_TYPES_LINKMAINVTO,
	EM_SUPPORT_LIFT_CONTROL_TYPES_LINkLIFTCONTROLHOST
}
