// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_SENSOR_ABNORMAL_STATUS

namespace BulkMaterialsForm.DH;

public enum EM_SENSOR_ABNORMAL_STATUS
{
	NET_SENSOR_ABNORMAL_STATUS_UNKNOWN,
	NET_SENSOR_ABNORMAL_STATUS_SHORT,
	NET_SENSOR_ABNORMAL_STATUS_BREAK,
	NET_SENSOR_ABNORMAL_STATUS_INTRIDED,
	NET_SENSOR_ABNORMAL_STATUS_MASK,
	NET_SENSOR_ABNORMAL_STATUS_NORMAL,
	NET_SENSOR_ABNORMAL_STATUS_OFFLINE,
	NET_SENSOR_ABNORMAL_STATUS_ALARM,
	NET_SENSOR_ABNORMAL_STATUS_FAULT
}
