// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_STORAGE_ERROR

namespace BulkMaterialsForm.DH;

public enum EM_STORAGE_ERROR
{
	STORAGE_ERROR_NONE,
	STORAGE_ERROR_PATITION,
	STORAGE_ERROR_INIT_FS,
	STORAGE_ERROR_READ_DATA,
	STORAGE_ERROR_WRITE_DATA,
	STORAGE_ERROR_RAID_FAILED,
	STORAGE_ERROR_RAID_DEGRADED,
	STORAGE_ERROR_ISCSI_FAILED
}
