// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_SPEAK_AUDIO_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_SPEAK_AUDIO_TYPE
{
	EM_SPEAK_AUDIO_TYPE_UNKNOWN,
	EM_SPEAK_AUDIO_TYPE_PCM,
	EM_SPEAK_AUDIO_TYPE_ADPCM,
	EM_SPEAK_AUDIO_TYPE_G711A,
	EM_SPEAK_AUDIO_TYPE_G711Mu,
	EM_SPEAK_AUDIO_TYPE_G726,
	EM_SPEAK_AUDIO_TYPE_G729,
	EM_SPEAK_AUDIO_TYPE_MPEG2,
	EM_SPEAK_AUDIO_TYPE_AMR,
	EM_SPEAK_AUDIO_TYPE_AAC
}
