// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_SCENE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_SCENE_TYPE
{
	EM_SCENE_UNKNOW,
	EM_SCENE_NORMAL,
	EM_SCENE_TRAFFIC,
	EM_SCENE_TRAFFIC_PATROL,
	EM_SCENE_FACEDETECTION,
	EM_SCENE_ATM,
	EM_SCENE_INDOOR,
	EM_SCENE_FACERECOGNITION,
	EM_SCENE_PS,
	EM_SCENE_NUMBERSTAT,
	EM_SCENE_HEAT_MAP,
	EM_SCENE_VIDEODIAGNOSIS,
	EM_SCENE_VEHICLEANALYSE,
	EM_SCENE_COURSERECORD,
	EM_SCENE_VEHICLE,
	EM_SCENE_STANDUPDETECTION,
	EM_SCENE_GATE,
	EM_SCENE_SDFACEDETECTION,
	EM_SCENE_HEAT_MAP_PLAN,
	EM_SCENE_NUMBERSTAT_PLAN,
	EM_SCENE_ATMFD,
	EM_SCENE_HIGHWAY,
	EM_SCENE_CITY,
	EM_SCENE_LETRACK,
	EM_SCENE_SCR,
	EM_SCENE_STEREO_VISION,
	EM_SCENE_HUMANDETECT,
	EM_SCENE_FACEANALYSIS,
	EM_SCENE_XRAY_DETECTION,
	EM_SCENE_STEREO_NUMBER,
	EM_SCENE_CROWD_DISTRI_MAP,
	EM_SCENE_OBJECTDETECT,
	EM_SCENE_FACEATTRIBUTE,
	EM_SCENE_FACECOMPARE,
	EM_SCENE_STEREO_BEHAVIOR,
	EM_SCENE_INTELLICITYMANAGER,
	EM_SCENE_PROTECTIVECABIN
}
