// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_STANDARD_VEHICLE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_STANDARD_VEHICLE_TYPE
{
	EM_STANDARD_VEHICLE_UNKNOWN,
	EM_STANDARD_VEHICLE_MOTOR,
	EM_STANDARD_VEHICLE_BUS,
	EM_STANDARD_VEHICLE_UNLICENSED_MOTOR,
	EM_STANDARD_VEHICLE_LARGE_CAR,
	EM_STANDARD_VEHICLE_MICRO_CAR,
	EM_STANDARD_VEHICLE_EMBASSY_CAR,
	EM_STANDARD_VEHICLE_MARGINAL_CAR,
	EM_STANDARD_VEHICLE_AREAOUT_CAR,
	EM_STANDARD_VEHICLE_FOREIGN_CAR,
	EM_STANDARD_VEHICLE_FARM_TRANS_CAR,
	EM_STANDARD_VEHICLE_TRACTOR,
	EM_STANDARD_VEHICLE_TRAILER,
	EM_STANDARD_VEHICLE_COACH_CAR,
	EM_STANDARD_VEHICLE_TRIAL_CAR,
	EM_STANDARD_VEHICLE_TEMPORARYENTRY_CAR,
	EM_STANDARD_VEHICLE_TEMPORARYENTRY_MOTORCYCLE,
	EM_STANDARD_VEHICLE_TEMPORARY_STEER_CAR,
	EM_STANDARD_VEHICLE_LARGE_TRUCK,
	EM_STANDARD_VEHICLE_MID_TRUCK,
	EM_STANDARD_VEHICLE_MICRO_TRUCK,
	EM_STANDARD_VEHICLE_MICROBUS,
	EM_STANDARD_VEHICLE_SALOON_CAR,
	EM_STANDARD_VEHICLE_CARRIAGE,
	EM_STANDARD_VEHICLE_MINI_CARRIAGE,
	EM_STANDARD_VEHICLE_SUV_MPV,
	EM_STANDARD_VEHICLE_SUV,
	EM_STANDARD_VEHICLE_MPV,
	EM_STANDARD_VEHICLE_PASSENGER_CAR,
	EM_STANDARD_VEHICLE_MOTOR_BUS,
	EM_STANDARD_VEHICLE_MID_PASSENGER_CAR,
	EM_STANDARD_VEHICLE_MINI_BUS,
	EM_STANDARD_VEHICLE_PICKUP,
	EM_STANDARD_VEHICLE_OILTANK_TRUCK
}
