// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_STREAM_PROTOCOL_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_STREAM_PROTOCOL_TYPE
{
	EM_STREAM_PROTOCOL_UNKNOWN,
	EM_STREAM_PROTOCOL_PRIVATE_V2,
	EM_STREAM_PROTOCOL_PRIVATE_V3,
	EM_STREAM_PROTOCOL_RTSP,
	EM_STREAM_PROTOCOL_ONVIF,
	EM_STREAM_PROTOCOL_GB28181,
	EM_STREAM_PROTOCOL_HIKVISION,
	EM_STREAM_PROTOCOL_BSCP
}
