// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_TRAFFICSTROBE_STATUS

namespace BulkMaterialsForm.DH;

public enum EM_TRAFFICSTROBE_STATUS
{
	NET_TRAFFICSTROBE_STATUS_UNKNOWN,
	NET_TRAFFICSTROBE_STATUS_CLOSE_COMPLETE,
	NET_TRAFFICSTROBE_STATUS_OPEN_COMPLETE,
	NET_TRAFFICSTROBE_STATUS_NOT_CLOSE_COMPLETE,
	NET_TRAFFICSTROBE_STATUS_NOT_OPEN_COMPLETE,
	NET_TRAFFICSTROBE_STATUS_NOT_STROBE_STOP
}
