// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_TRAFFIC_SNAP_DEVICE_WORK_STATE

namespace BulkMaterialsForm.DH;

public enum EM_TRAFFIC_SNAP_DEVICE_WORK_STATE
{
	EM_TRAFFIC_SNAP_DEVICE_WORK_STATE_UNKNOWN = -1,
	EM_TRAFFIC_SNAP_DEVICE_WORK_STATE_FAULT,
	EM_TRAFFIC_SNAP_DEVICE_WORK_STATE_NORMAL,
	EM_TRAFFIC_SNAP_DEVICE_WORK_STATE_CLOSE
}
