// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_TRAFFIC_SNAP_GROUND_SENSE_IN_STATE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_TRAFFIC_SNAP_GROUND_SENSE_IN_STATE_TYPE
{
	EM_TRAFFIC_SNAP_GROUND_SENSE_IN_STATE_TYPE_UNKNOWN = -1,
	EM_TRAFFIC_SNAP_GROUND_SENSE_IN_STATE_TYPE_NO_CAR = 0,
	EM_TRAFFIC_SNAP_GROUND_SENSE_IN_STATE_TYPE_CAR = 1,
	EM_TRAFFIC_SNAP_GROUND_SENSE_IN_STATE_TYPE_NO_SUPPORT = 255
}
