// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_TRAFFIC_SNAP_STROBE_RUN_STATE

namespace BulkMaterialsForm.DH;

public enum EM_TRAFFIC_SNAP_STROBE_RUN_STATE
{
	EM_TRAFFIC_SNAP_STROBE_RUN_STATE_UNKNOWN = -1,
	EM_TRAFFIC_SNAP_STROBE_RUN_STATE_CLOSE,
	EM_TRAFFIC_SNAP_STROBE_RUN_STATE_OPEN,
	EM_TRAFFIC_SNAP_STROBE_RUN_STATE_OPENING,
	EM_TRAFFIC_SNAP_STROBE_RUN_STATE_CLOSING,
	EM_TRAFFIC_SNAP_STROBE_RUN_STATE_STOP
}
