// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_TOLLS_VEHICLE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_TOLLS_VEHICLE_TYPE
{
	EM_TOLLS_VEHICLE_TYPE_UNKNOWN = 0,
	EM_TOLLS_VEHICLE_TYPE_PASSENGER_CAR1 = 1,
	EM_TOLLS_VEHICLE_TYPE_PASSENGER_CAR2 = 2,
	EM_TOLLS_VEHICLE_TYPE_PASSENGER_CAR3 = 3,
	EM_TOLLS_VEHICLE_TYPE_PASSENGER_CAR4 = 4,
	EM_TOLLS_VEHICLE_TYPE_TRUCK1 = 11,
	EM_TOLLS_VEHICLE_TYPE_TRUCK2 = 12,
	EM_TOLLS_VEHICLE_TYPE_TRUCK3 = 13,
	EM_TOLLS_VEHICLE_TYPE_TRUCK4 = 14,
	EM_TOLLS_VEHICLE_TYPE_TRUCK5 = 15,
	EM_TOLLS_VEHICLE_TYPE_TRUCK6 = 16,
	EM_TOLLS_VEHICLE_TYPE_OPERATION_VEHICLE1 = 21,
	EM_TOLLS_VEHICLE_TYPE_OPERATION_VEHICLE2 = 22,
	EM_TOLLS_VEHICLE_TYPE_OPERATION_VEHICLE3 = 23,
	EM_TOLLS_VEHICLE_TYPE_OPERATION_VEHICLE4 = 24,
	EM_TOLLS_VEHICLE_TYPE_OPERATION_VEHICLE5 = 25,
	EM_TOLLS_VEHICLE_TYPE_OPERATION_VEHICLE6 = 26
}
