// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_TRAFFIC_SNAP_STROBE_IN_STATE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_TRAFFIC_SNAP_STROBE_IN_STATE_TYPE
{
	EM_TRAFFIC_SNAP_STROBE_IN_STATE_TYPE_UNKNOWN = -1,
	EM_TRAFFIC_SNAP_STROBE_IN_STATE_TYPE_TO_BREAK_OFF = 0,
	EM_TRAFFIC_SNAP_STROBE_IN_STATE_TYPE_CLOSE = 1,
	EM_TRAFFIC_SNAP_STROBE_IN_STATE_TYPE_NO_SUPPORT = 255
}
