// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_TRAFFICCAR_LANE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_TRAFFICCAR_LANE_TYPE
{
	EM_TRAFFICCAR_LANE_TYPE_UNKNOWN,
	EM_TRAFFICCAR_LANE_TYPE_NORMAL,
	EM_TRAFFICCAR_LANE_TYPE_NONMOTOR,
	EM_TRAFFICCAR_LANE_TYPE_LIGHT_DUTY,
	EM_TRAFFICCAR_LANE_TYPE_BUS,
	EM_TRAFFICCAR_LANE_TYPE_EMERGENCY,
	EM_TRAFFICCAR_LANE_TYPE_DANGEROUS,
	EM_TRAFFICCAR_LANE_TYPE_TIDAL
}
