// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_UNIFORM_STYLE

namespace BulkMaterialsForm.DH;

public enum EM_UNIFORM_STYLE
{
	EM_UNIFORM_STYLE_UNKNOWN,
	EM_UNIFORM_STYLE_POLICE,
	EM_UNIFORM_STYLE_NOUNIFORM,
	EM_UNIFORM_STYLE_SINOPEC,
	EM_UNIFORM_STYLE_GUARD,
	EM_UNIFORM_STYLE_VEST,
	EM_UNIFORM_STYLE_SATNITATION,
	EM_UNIFORM_STYLE_TAKEOUT,
	EM_UNIFORM_STYLE_JUN,
	EM_UNIFORM_STYLE_EXPRESS,
	EM_UNIFORM_STYLE_SECURITY
}
