// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_USERMANAGER_IMAGE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_USERMANAGER_IMAGE_TYPE
{
	EM_USERMANAGER_IMAGE_TYPE_UNKNOWN = -1,
	EM_USERMANAGER_IMAGE_TYPE_LOCAL,
	EM_USERMANAGER_IMAGE_TYPE_SCENE,
	EM_USERMANAGER_IMAGE_TYPE_FACE,
	EM_USERMANAGER_IMAGE_TYPE_INFRARED,
	EM_USERMANAGER_IMAGE_TYPE_ENTOURAGE,
	EM_USERMANAGER_IMAGE_TYPE_THERMOGRAM
}
