// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_VIDEO_ABNORMAL_DETECT_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_VIDEO_ABNORMAL_DETECT_TYPE
{
	EM_VIDEO_ABNORMAL_DETECT_UNKNOWN,
	EM_VIDEO_ABNORMAL_DETECT_LOSS,
	EM_VIDEO_ABNORMAL_DETECT_COVER,
	EM_VIDEO_ABNORMAL_DETECT_FROZEN,
	EM_VIDEO_ABNORMAL_DETECT_LIGHT,
	EM_VIDEO_ABNORMAL_DETECT_DARK,
	EM_VIDEO_ABNORMAL_DETECT_SCENECHANGE,
	EM_VIDEO_ABNORMAL_DETECT_STRIATION,
	EM_VIDEO_ABNORMAL_DETECT_NOISE,
	EM_VIDEO_ABNORMAL_DETECT_UNBALANCE,
	EM_VIDEO_ABNORMAL_DETECT_BLUR,
	EM_VIDEO_ABNORMAL_DETECT_CONTRAST,
	EM_VIDEO_ABNORMAL_DETECT_MOTION,
	EM_VIDEO_ABNORMAL_DETECT_FILCKERING,
	EM_VIDEO_ABNORMAL_DETECT_COLOR,
	EM_VIDEO_ABNORMAL_DETECT_UNFOCUS,
	EM_VIDEO_ABNORMAL_DETECT_OVEREXPOSURE,
	EM_VIDEO_ABNORMAL_DETECT_DRAMATICCHANGE,
	EM_VIDEO_ABNORMAL_DETECT_BLACKWHITE,
	EM_VIDEO_ABNORMAL_DETECT_SNOWNOISE
}
