// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_VEHICLE_ATTACHMENT_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_VEHICLE_ATTACHMENT_TYPE
{
	EM_VEHICLE_ATTACHMENT_TYPE_UNKNOWN,
	EM_VEHICLE_ATTACHMENT_TYPE_FURNITURE,
	EM_VEHICLE_ATTACHMENT_TYPE_PENDANT,
	EM_VEHICLE_ATTACHMENT_TYPE_TISSUE_BOX,
	EM_VEHICLE_ATTACHMENT_TYPE_PERFUME_BOX,
	EM_VEHICLE_ATTACHMENT_TYPE_DANGER,
	EM_VEHICLE_ATTACHMENT_TYPE_NONE,
	EM_VEHICLE_ATTACHMENT_TYPE_CARD
}
