// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_VIDEO_PLAY_OPERATE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_VIDEO_PLAY_OPERATE_TYPE
{
	EM_VIDEO_PLAY_OPERATE_TYPE_UNKNOWN,
	EM_VIDEO_PLAY_OPERATE_TYPE_REPLACE,
	EM_VIDEO_PLAY_OPERATE_TYPE_ADD,
	EM_VIDEO_PLAY_OPERATE_TYPE_REMOVE,
	EM_VIDEO_PLAY_OPERATE_TYPE_CLEAR
}
