// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_VEHICLE_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_VEHICLE_TYPE
{
	EM_VEHICLE_TYPE_UNKNOWN,
	EM_VEHICLE_TYPE_PASSENGERCAR1,
	EM_VEHICLE_TYPE_TRUCK1,
	EM_VEHICLE_TYPE_PASSENGERCAR2,
	EM_VEHICLE_TYPE_TRUCK2,
	EM_VEHICLE_TYPE_PASSENGERCAR3,
	EM_VEHICLE_TYPE_TRUCK3,
	EM_VEHICLE_TYPE_PASSENGERCAR4,
	EM_VEHICLE_TYPE_TRUCK4,
	EM_VEHICLE_TYPE_PASSENGERCAR5,
	EM_VEHICLE_TYPE_TRUCK5
}
