// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_WATER_DETECTION_ALARM_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_WATER_DETECTION_ALARM_TYPE
{
	EM_WATER_DETECTION_ALARM_TYPE_UNKNOWN,
	EM_WATER_DETECTION_ALARM_TYPE_QUALITY,
	EM_WATER_DETECTION_ALARM_TYPE_PH,
	EM_WATER_DETECTION_ALARM_TYPE_NTU,
	EM_WATER_DETECTION_ALARM_TYPE_NH3_N,
	EM_WATER_DETECTION_ALARM_TYPE_TN,
	EM_WATER_DETECTION_ALARM_TYPE_SD,
	EM_WATER_DETECTION_ALARM_TYPE_COD,
	EM_WATER_DETECTION_ALARM_TYPE_NN,
	EM_WATER_DETECTION_ALARM_TYPE_DO,
	EM_WATER_DETECTION_ALARM_TYPE_CHL_A,
	EM_WATER_DETECTION_ALARM_TYPE_TP,
	EM_WATER_DETECTION_ALARM_TYPE_CODMN,
	EM_WATER_DETECTION_ALARM_TYPE_SS,
	EM_WATER_DETECTION_ALARM_TYPE_BOD_5,
	EM_WATER_DETECTION_ALARM_TYPE_NO3_N,
	EM_WATER_DETECTION_ALARM_TYPE_TSI,
	EM_WATER_DETECTION_ALARM_TYPE_SMELLY_LEVEL
}
