// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.EM_WORKSTATDETECTION_TYPE

namespace BulkMaterialsForm.DH;

public enum EM_WORKSTATDETECTION_TYPE
{
	EM_WORKSTATDETECTION_UNKNOWN,
	EM_WORKSTATDETECTION_NO_WORKER,
	EM_WORKSTATDETECTION_SINGLE_WORKER,
	EM_WORKSTATDETECTION_NO_WORKER_LEADER,
	EM_WORKSTATDETECTION_HAND_DISINFECTION,
	EM_WORKSTATDETECTION_FOOT_DIP,
	EM_WORKSTATDETECTION_SHOES_CHANGE
}
