// Decompiled from: BulkMaterialsForm.exe
// Namespace: BulkMaterialsForm.DH
// Type: BulkMaterialsForm.DH.NET_EM_ACCESS_CTL_MANAGER

namespace BulkMaterialsForm.DH;

public enum NET_EM_ACCESS_CTL_MANAGER
{
	MANAGER_ADDDEVICE,
	MANAGER_MODIFYDEVICE,
	MANAGER_REMOVEDEVICE,
	GETSUBCONTROLLER_INFO,
	GETSUBCONTROLLER_STATE,
	SET_REPEAT_ENTERROUTE,
	GET_REPEAT_ENTERROUTE,
	SET_ABLOCK_ROUTE,
	GET_ABLOCK_ROUTE,
	GET_LOGSTATUS,
	SYNCHRO_OFFLINE_LOG,
	SYNCHRO_TIME,
	SET_QRCODEDECODE_INFO
}
